### ISSUE TITLE
Support for net45, and/or netstandard1.1?

### ISSUE THREAD

**Issue by fubar-coder** [jfrijters/Managed.Reflection#1]
It would be nice if the new IKVM (and this Managed.Reflection project) would be usable from a .NET 4.5 project. The main reason for this request is, that - when using C++/CLI from VS2013 (netstandard1.1) - you can only use .NET 4.5. When you use VS2015, you can use .NET 4.5.2, but that means netstandard1.2. I guess that it's the easiest way to just use netstandard1.3 and net45, because netstandard1.2 already lacks some APIs that might be required...

Here's a link to the [net-platform-standard document](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) of the [corefx](https://github.com/dotnet/corefx) repository.

**Comment by jfrijters** [comment]
IKVM still targets .NET 3.5 and up and IKVM.Reflection will continue to be available in the foreseeable future. Managed.Reflection targets .NET Standard 1.3, because it needs the crypto APIs.

**Comment by fubar-coder** [comment]
That's part of the problem. .NET 4.5 framework references are quite different from pre .NET 4.5 framework references. I hoped that I could avoid all those problems when targeting both .NET Core and .NET Framework. An additional framework target net45 would really help in this regard. This would also mean, that my libraries dependency aren't different depending on the target framework, which would avoid problems for users of my library.

**Comment by jfrijters** [comment]
Managed.Reflection doesn't offer any help (at the moment anyway) with locating reference assemblies and you need to do essentially the same as IKVM.Reflection required to target a specific framework.

**Comment by fubar-coder** [comment]
Ah, ok, I guess there is a misunderstanding here.

My problem as follows is:

I have a JAR that I have to convert/use. My assumption was, that this library is the foundation of the new IKVM. After the conversion, both the IKVM JAVA compatibility libraries and the converted JAR should be available for net45 and netstandard1.3, because I need to use the converted library in projects targeting netcoreapp1.0 and net452.

My use case is quite specific and I just wanted to issue a ticket at this early stage.

EDIT: some clarifications

**Comment by jfrijters** [comment]
This library is not related to IKVM. IKVM will continue to evolve by itself and when I stop supporting .NET 3.5, it will probably go to .NET 4.5, but .NET Core 1.0 support is very unlikely.
