### ISSUE TITLE
Question: Does ppdb in MR support local variables?

### ISSUE THREAD

**Issue by borgdylan** [jfrijters/Managed.Reflection#5]
Is Managed.Reflection generating the information related to local variables on which SetLocalSymInfo is called. When using roslyn, I see variables (named as in the source code) for both mono and coreclr. When using Managed.Reflection, mono shows V_0, V_1 etc. for local variable names (not the ones I set) wheres for coreclr the variables do not appear at all.

**Comment by jfrijters** [comment]
Yes. I have tested it with Visual Studio.

**Comment by borgdylan** [comment]
Therefore is SetLocalSymInfo enough to set names for variables and paramaters? For parameters I also set the names in metadata using a ParameterBuilder.

**Comment by borgdylan** [comment]
If yes, then I need to check that I am indeed calling SetLocalSymInfo.

**Comment by jfrijters** [comment]
Yes, calling SetLocalSymInfo is enough. I should say that I have only tested with trivial code. So there could still be a bug.

**Comment by borgdylan** [comment]
Did that code include local variables i.e. not just parameters?

**Comment by jfrijters** [comment]
Yes.

**Comment by borgdylan** [comment]
Do you refer to documents using relative or full paths?

**Comment by jfrijters** [comment]
I just pushed [9b27f02](https://github.com/jfrijters/Managed.Reflection/commit/9b27f0299a78270114d06e1e4caf4cda30ec91a4) to fix a bug related to local variable scopes. That might be the problem you're seeing.

**Comment by jfrijters** [comment]
A document is just an opaque string. It gets stored as-is.

**Comment by borgdylan** [comment]
I was using cat and less, and managed to spot document urls and variable names. I admit that I could not understand the garbled text around those strings as its all binary.

**Comment by jfrijters** [comment]
I don't yet compress the document urls. That makes no functional difference, but it does waste a bit of space.

**Comment by borgdylan** [comment]
I am trying your changes. Will report back when testing is done.

**Comment by borgdylan** [comment]
In coreclr I am not seeing the variables, with mono it is using variable names from other methods.

**Comment by borgdylan** [comment]
In my main method that has three variables, I am only seeing the first one using the name from the only variable in another method. I also happen to have many methods that use variables named the same.

**Comment by borgdylan** [comment]
In case it has any effect, I only pass a name to SetLocalSymInfo without any offsets for start and finish.

**Comment by jfrijters** [comment]
Thanks. That was the clue I needed (seeing the variables from another method). Working on a fix.

**Comment by jfrijters** [comment]
Pushed [0bc91b4](https://github.com/jfrijters/Managed.Reflection/commit/0bc91b425cb8c2f77a1a932c0f01f7b28e699d2f) to fix this.

**Comment by borgdylan** [comment]
The issue has been resolved 100%. I just need to give temp vars a name in syminfo. Currently I am passing in an empty string. Mono ignores them (what I wanted) but the coreclr debugger shows them as empty. I will give them unique names programmatically and release anew compiler patch. Thanks and have a nice day.

**Comment by jfrijters** [comment]
Thanks!

**Comment by borgdylan** [comment]
I will be happy to test any changes that affects my compiler. After all, mcs may end up using Managed.Reflection.
